### ISSUE TITLE
Heights of superscripts and subscripts

### ISSUE THREAD

**Issue by sunnyssk** [firamath/firamath#16]
I am trying the v0.3 otf release in MS Word these days and found the superscripts/subscripts are not behaving as expected:

![default](https://user-images.githubusercontent.com/19568216/45652693-73cc3b00-baa3-11e8-99d0-ab0b2579705d.png)

Basically, regardless of extension of the delimiters themselves, the superscripts/subscripts will stay at the same height from the baseline. Are thay designed to behave in this way, or influenced by other factors?

**Comment by YuanshengZhao** [comment]
在MSW里面我那个字体也会出bug,目前原因不明.

**Comment by stone-zeng** [comment]
It should OK now after setting the `IsExtendedShape` flag to be `1` for these glyphs:
![image](https://user-images.githubusercontent.com/18233088/45770984-79c64580-bc76-11e8-9b6e-085afb6450db.png)
