### ISSUE TITLE
Multi-weight math font support in MS Word

### ISSUE THREAD

**Issue by stone-zeng** [firamath/firamath#17]
It seems that MS Word does not support multi-weight math font. Only 4/5 weights can be found in the "Equation Options" (Bold version is missing). And at the same time, `FiraMath-Regular` can't be used normally.

Note that the family name of `FiraMath-Regular` and `FiraMath-Bold` are both `Fira Math`, so I guess it's related to this point.

**Comment by be5invis** [comment]
There is a concept called "style linking". Though I am not sure whether weights are supported in MSO math env. Maybe you can try to split the family names in Name ID 1/2.
(Murray Sargent, who made almost everything in Office about equations, does not use GitHub 😞. )
