### ISSUE TITLE
Monospaced symbols

### ISSUE THREAD

**Issue by stone-zeng** [firamath/firamath#19]
Sometimes it's necessary to make `+`/`-`, `=`/`<`/`>` etc to have the same width, for example in `align` environment. See [How can I redefine the minus sign to be of the same width as plus?](https://tex.stackexchange.com/q/364147/136923).

Still need to check whether these symbols are *really* monospaced when typed.

Maybe I need another stylistic set for proportional/monospaced things.

**Comment by hvoss49** [comment]
It make more sense to create a complete monospaced math font.

Am Mo., 22. Okt. 2018 um 18:14 Uhr schrieb Xiangdong Zeng <
notifications@github.com>:

**Comment by stone-zeng** [comment]
A related issue can be found in <https://github.com/OpenType/opentype-layout/issues/11>. But at present, it's still under discussion how to implement a "fullly monospaced" math font.
