### ISSUE TITLE
More glyphs

### ISSUE THREAD

**Issue by YuanshengZhao** [firamath/firamath#2]
- [x] `\hbar`
- [x] `\propto`
- [ ] extensible arrows
- [x] arrows
- [x] `\parallel`, `perp`
- [x] `\in`, `\ni`
- [x] `\mathbb`
- [ ] `\mathcal`
- [ ] stylistic set for `1` and `4`
- [x] large root
- [ ] `\bigcup`

**Comment by sunnyssk** [comment]
Hope there would also be \oint in the .otf release if possible.

**Comment by stone-zeng** [comment]
`\oint`, `\oiint` etc. have been made already, and I will public a release after some minor updates.

**Comment by stone-zeng** [comment]
Most of the things have been tracked in other issues: #11, #12, #13, #14. So closed now.
