### ISSUE TITLE
Firamath light  missing \sum glyph

### ISSUE THREAD

**Issue by sconan32** [firamath/firamath#21]
firamath light missing \sum glyph 
How about coping the missing glyphs from regular version when generating fonts.

**Comment by YuanshengZhao** [comment]
IMO, assuming using TeX with `unicode-math` package, it is better to use the `range` option at present. Mixing fonts on the font level can be somewhat messy, since one may fail to notice that one glyph has not been made.

**Comment by beojan** [comment]
Unfortunately, all you can do with the range option is swap out digits and Latin and Greek letters. You can't import only the missing glyphs.

It also doesn't work with math versions, so you can't use `boldmath`.

**Comment by stone-zeng** [comment]
If you need this glyph now, I can add it temporarily.

**Comment by sconan32** [comment]
Thanks for the replies.
I decided using regular version instead.

**Comment by stone-zeng** [comment]
Now the display style of `\sum` has been added in v0.4-beta-2 for all weights.
