### ISSUE TITLE
Inconsistent horizontal advances for hyphens

### ISSUE THREAD

**Issue by RuixiZhang42** [firamath/firamath#24]
There is inconsistency within the four hyphens:

| Unicode | Horizontal advance |
|:---:|:---:|
| `U+002D` | 403 |
| `U+00AD` | 403 |
| `U+2010` | 327 |
| `U+2011` | 327 |

Please consider fixing `U+2010` and `U+2011` so that their horizontal advances are also `403`.

**Comment by RuixiZhang42** [comment]
A short example illustrating the inconsistency:

    % !TeX program = XeLaTeX
    \documentclass{article}
    \usepackage{amsmath}
    \DeclareMathOperator\ResIm{Res-Im}% U+002D
    \usepackage[mathrm=sym]{unicode-math}
    \setmathfont{Fira Math}
    \begin{document}
    $\ResIm(z)$ \texttt{U+002D}\par
    $\mathrm{Res‐Im}(z)$ \texttt{U+2010}\par
    $\mathrm{Res‑Im}(z)$ \texttt{U+2011}
    \end{document}

![inconsistent](https://user-images.githubusercontent.com/39968857/49979015-179a7b00-ff1b-11e8-9173-4523eb62b604.png)

**Comment by stone-zeng** [comment]
These glyphs are directly copied from FiraGO, but it really looks like a bug:

![image](https://user-images.githubusercontent.com/18233088/50004985-be4a4e80-ffe3-11e8-8412-40786bae81d2.png)

I don't think there is a special reason to make the hyphen go outside the boundary, especially compare with other weights:

![image](https://user-images.githubusercontent.com/18233088/50005311-ec7c5e00-ffe4-11e8-975d-fbd58dec47ab.png)

IMHO, these characters should looks identical and I will fix it.

**Comment by stone-zeng** [comment]
See <https://github.com/bBoxType/FiraGO/issues/26>.

**Comment by stone-zeng** [comment]
It should already be fixed:

<img width="586" alt="Screen Shot 2021-06-11 at 03 44 58" src="https://user-images.githubusercontent.com/18233088/121587442-66cbb300-ca67-11eb-8bc7-fdcda6926f38.png">
