### ISSUE TITLE
Issues related to multiple weights

### ISSUE THREAD

**Issue by stone-zeng** [firamath/firamath#27]
I have merged `weights` branch into `master`, but there are still numerous problems. If you have found any problems (except for the known issues listed below), please comment here.

Known issues:

- [ ] Only few of the basic glyphs have been created. I need some time to cover them.
- [x] Interpolated points are not rounded to integer, and overlapped paths are not removed.
- [ ] Now the metrics are just from the original FiraGO/FiraSans, but should be modified for math.
- [x] For primes, `ssty2` is identical to `ssty1`. See <https://github.com/wspr/unicode-math/issues/503>.
- [x] Mathematical Capital Theta Symbols are not correct.

**Comment by krrk** [comment]
I believe that superscript minus doesn't work with the light weight. For example in `$10^{-1}$` the minus is not shown in the output PDF. I'm using lualatex.

**Comment by stone-zeng** [comment]
This is simply because I haven't create the minus character (U+2212)...

**Comment by krrk** [comment]
Okay, I see. Thanks

**Comment by beojan** [comment]
The big thing I'm missing right now is that there's no `\rightarrow` (or `\to`) in the other weights.

EDIT: Big delimeters are also missing.
You could consider copying some of these symbols from [MdSymbol](https://github.com/sebschub/MdSymbol)

**Comment by stone-zeng** [comment]
@krrk @beojan Minus, rightarrow, etc have been added in 688cce705995f943b2b4a6689f8a6d54bafdd337 and 3e23983539bcec76a617355ec4a2d02367d905e2.

**Comment by krrk** [comment]
Thanks!
