### ISSUE TITLE
CTAN submission ?

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [firamath/firamath#3]
Wouldn't it be nice to have this font (and possibly a support style file) submitted to CTAN for inclusion in  TeXlive ? I think it's too late for 2018, but it would be nice to have it in TeXlive 2019...

**Comment by stone-zeng** [comment]
Sorry for the late reply. I will consider to upload the font to CTAN when it's almost finished (too many glyphs still not added now).

Anyway, to use this font in LaTeX, you just need to download the otf file (can be found in release), install it on your OS (optional), then use the `fontspec` package in LaTeX.

**Comment by hvoss49** [comment]
I'll create a package `firamath-otf` which uses at first only the regular version. It can be extended later. The only problem is that LuaTeX do not use a feature file in the current version. It defines all with Luacode

**Comment by stone-zeng** [comment]
I have upload the version 0.3. The name on CTAN is `firamath`, see <https://ctan.org/pkg/firamath>.

**Comment by stone-zeng** [comment]
@hvoss49 What happened about [`firamath-otf`](https://ctan.org/pkg/firamath-otf)? I think these two packages should be merged.

**Comment by gipert** [comment]
Hi, you should provide a `firamath.sty` like in `firamath-otf`, otherwise `\usepackage{firamath}` won't work... Or the package is meant to be used differently?

**Comment by hvoss49** [comment]
No, Fira Math is an open type font. A package `firamath` makes sense when there is also a Type1 version. Just like package `libertinus` which loads `libertinus-type1` or `libertinus-otf`, depending to the used TeX engine.

**Comment by hvoss49** [comment]
> @hvoss49 What happened about [`firamath-otf`](https://ctan.org/pkg/firamath-otf)? I think these two packages should be merged.

Yes and no. I suppose that someone will create also type 1 versions of the fonts. Then it make sense to have four packages:

firamath-fonts   
firamath-sty   (Only  a wrapper for the follwong two packages)
firsmath-type1
firamath-otf

**Comment by stone-zeng** [comment]
I hope to merge them together. Using four packages for a single font is really annoying. And, I think it's unnecessary to made the type1 version. XITS and tex-gyre, for example, are only available under opentype.

**Comment by hvoss49** [comment]
> I hope to merge them together. Using four packages for a single font is really annoying. And, I think it's unnecessary to made the type1 version. XITS and tex-gyre, for example, are only available under opentype.

It is not a question of necessary or not. If someone creates the type 1 versions from your otf one, then there is a need for such a package. Compare Libertinus, STIX, and so on ...

**Comment by stone-zeng** [comment]
So I will keep the things there.
