### ISSUE TITLE
Integral bounds are misplaced

### ISSUE THREAD

**Issue by ma-sadeghi** [firamath/firamath#30]
![integral_bounds_misplaced](https://user-images.githubusercontent.com/14086031/52902205-e3be2900-31db-11e9-9931-332bde98f0a5.PNG)

**Comment by stone-zeng** [comment]
Could you please provide the version of firamath font and the LaTeX code (if used) of your example?

**Comment by ma-sadeghi** [comment]
> Could you please provide the version of firamath font and the LaTeX code (if used) of your example?

FiraMath v0.4-beta-2
`\int_a^b` + space + `f(x)dx`

EDIT: I just realized when I use Fira Math instead of Fira Math Book, the problem gets solved.

**Comment by stone-zeng** [comment]
I guess you are using inline math mode (i.e. `$...$`). The problem is that the inline integrals haven't been created (except for Regular weight), so they will fallback to the display style.

I will add them later.

**Comment by stone-zeng** [comment]
Now the inline version should be available in *all* the weights:

![image](https://user-images.githubusercontent.com/18233088/53033641-7563ba00-34ac-11e9-94ce-dbe9ec1bd942.png)

**Comment by stone-zeng** [comment]
I'm afraid that it's still not perfect:

![image](https://user-images.githubusercontent.com/18233088/53381616-449feb00-39ac-11e9-90d3-6ce52bcd74ca.png)

This is on MS Word for Mac version 16.22. Note that the weight selection and line spacing etc are in a mess too.

**Comment by stone-zeng** [comment]
This issue is due to that I haven't set `IsExtendedShape` to be true for the other weights.

**Comment by stone-zeng** [comment]
![image](https://user-images.githubusercontent.com/18233088/57176455-f404ac80-6e8a-11e9-83f7-8ef290429454.png)

Note that the spacing of subscripts are not correct (since I haven't adjust them). The bold and heavier weights are not correct either, and I guess it's ms word's bug.

I use Microsoft Word for Mac Version 16.25 (19050200) here.
