### ISSUE TITLE
Some incorrectly mapped characters

### ISSUE THREAD

**Issue by RuixiZhang42** [firamath/firamath#31]
First of all, congratulations on Fira Math appearing in the newest [`unimath-symbols.pdf`](http://mirrors.ctan.org/macros/latex/contrib/unicode-math/unimath-symbols.pdf) since `v0.8n` of [`unicode-math`](https://github.com/wspr/unicode-math)!!!

I&nbsp;glanced through that comprehensive list provided by `unimath-symbols.pdf` and found 4 incorrectly mapped characters so far:

```tex
\documentclass{article}
\usepackage{unicode-math}
\setmathfont{[FiraMath-Regular.otf]}[version=F]% either v0.3.1 or v0.4-beta-2
\setmathfont{latinmodern-math.otf}[version=L]
\setmathfont{texgyrepagella-math.otf}[version=P]
\setmathfont{STIX2Math.otf}[version=S]
\newcommand*\compare[1]{%
  \texttt{\string#1} &
  \mathversion{F}$#1$ &
  \mathversion{L}$#1$ &
  \mathversion{P}$#1$ &
  \mathversion{S}$#1$%
}
\renewcommand*\arraystretch{1.2}
\usepackage{array}
\begin{document}
\begin{tabular}{>{\ttfamily}llllll}
USV & Command name & F & L & P & S \\
\hline
U+025DE & \compare\lrarc \\
U+025DF & \compare\llarc \\
U+021CB & \compare\leftrightharpoons \\
U+021CC & \compare\rightleftharpoons \\
\end{tabular}
\end{document}
```

![ppp](https://user-images.githubusercontent.com/39968857/52917474-0161c000-32ba-11e9-9dd7-7bbf131c4fde.png)

An update to the CTAN version (without multiple weights if they are not ready) would be great.

**Comment by stone-zeng** [comment]
I'm afraid that I will not push it to CTAN now since the regular weight itself has been modified when doing the multi-weights, and the version will be in a mess either.
