### ISSUE TITLE
\circ glyph is missing

### ISSUE THREAD

**Issue by rolfn** [firamath/firamath#34]
Firamath does not provide a character for `\circ`. See the following example:
```latex
\listfiles
\documentclass{article}
\usepackage{amsmath}
\usepackage[mathrm=sym]{unicode-math}
\setmathfont{Fira Math}

\begin{document}
\Huge
20\,${}^{\circ}$C
\end{document}
```

...Rolf

**Comment by allanleal** [comment]
Is there any workaround for this (e.g., automatically resorting to another font that has symbol `\circ`)? I'm also having this issue.

**Comment by ArchangeGabriel** [comment]
Yes, just add `\setmathfont[range=\circ]{someotherfontthathasit}` after your first `\setmathfont`.

**Comment by allanleal** [comment]
Great. Any recommendation for `someotherfontthathasit` that looks closer to FiraSans? I know, circ is quite simple, but maybe in the future other symbols might be needed (and missing in FiraMath) and a more similar font to FiraSans preferred for this.

**Comment by ArchangeGabriel** [comment]
There is a list of fonts here: https://github.com/wspr/unicode-math/

Maybe one of the TeX Gyre fonts could suit you.

**Comment by ArchangeGabriel** [comment]
Also, @rolfn, please don’t use `\circ` for degrees. The symbol exists in ASCII (°), and for typesetting units there is the great `siunitx` package.

**Comment by stone-zeng** [comment]
For Celsius degree, personally I will use the following:

```latex
\documentclass{article}
\usepackage{unicode-math,siunitx}
\unimathsetup{math-style=ISO, bold-style=ISO, mathrm=sym}
\setmathfont{FiraMath-Regular.otf}
\sisetup{math-celsius=^^b0\kern-0.1emC}

\begin{document}
\SI{20}{\degreeCelsius}
$\SI{20}{\degreeCelsius}$
\end{document}
```

`^^b0` is U+00B0 DEGREE SIGN (°), followed by a `\kern` to decrease the space.

**Comment by rolfn** [comment]
@ArchangeGabriel This was only a simple example to show the problem. Of course I often use `siunitx`. `siunitx` is not a solution if the glyph is missing:
```
\listfiles
\documentclass{article}
\usepackage{amsmath}
\usepackage[mathrm=sym]{unicode-math}
\setmathfont{Fira Math}
\usepackage{siunitx}
\begin{document}
\Huge
\SI{20}{\degreeCelsius}
\end{document}
```

**Comment by stone-zeng** [comment]
`\circ`, or identically `\vysmwhtcircle`, is U+2218 RING OPERATOR. There are different sizes of circles in Unicode, listed here for reference:

| Glyph    | USV    | Unicode Name              | LaTeX command    |
|:--------:|:------:|:-------------------------:|:----------------:|
| &#x2218; | U+2218 | RING OPERATOR             | `\vysmwhtcircle` |
| &#x25E6; | U+25E6 | WHITE BULLET              | `\smwhtcircle`   |
| &#x26AC; | U+26AC | MEDIUM SMALL WHITE CIRCLE | `\mdsmwhtcircle` |
| &#x26AA; | U+26AA | MEDIUM WHITE CIRCLE       | `\mdwhtcircle`   |
| &#x25CB; | U+25CB | WHITE CIRCLE              | `\mdlgwhtcircle` |
| &#x25EF; | U+25EF | LARGE CIRCLE              | `\lgwhtcircle`   |

| Glyph    | USV    | Unicode Name              | LaTeX command    |
|:--------:|:------:|:-------------------------:|:----------------:|
| &#x2219; | U+2219 | BULLET OPERATOR           | `\vysmblkcircle` |
| &#x2022; | U+2022 | BULLET                    | `\smblkcircle`   |
| &#x2981; | U+2981 | Z NOTATION SPOT           | `\mdsmblkcircle` |
| &#x26AB; | U+26AB | MEDIUM BLACK CIRCLE       | `\mdblkcircle`   |
| &#x25CF; | U+25CF | BLACK CIRCLE              | `\mdlgblkcircle` |
| &#x2B24; | U+2B24 | BLACK LARGE CIRCLE        | `\lgblkcircle`   |
| &#x00B7; | U+00B7 | MIDDLE DOT                | `\cdotp`         |
| &#x2024; | U+2024 | ONE DOT LEADER            |                  |
| &#x2027; | U+2027 | HYPHENATION POINT         |                  |
| &#x22C5; | U+22C5 | DOT OPERATOR              | `\cdot`          |
| &#x2E31; | U+2E31 | WORD SEPARATOR MIDDLE DOT |                  |
| &#x2E33; | U+2E33 | RAISED DOT                |                  |

For the ones you need, I will add it as soon as possible.

PS: `siunitx` uses U+2218 for `\degreeCelsius` by default. @rolfn

**Comment by allanleal** [comment]
Awesome. Thanks @stone-zeng .

**Comment by allanleal** [comment]
OK, tried `\mdwhtcircle` and this resulted in `Missing character: There is no ⚪ in font Fira Math Regular/OT:script=math;language=DFLT;+ssty=0;!`

For this, I have in the preamble:

~~~latex
\renewcommand{\circ}{\mdwhtcircle} % FiraMath so far has no \circ
~~~

**Comment by rolfn** [comment]
> For the ones you need, I will add it as soon as possible.
> 
Thank you.
