### ISSUE TITLE
Math operators are small

### ISSUE THREAD

**Issue by RuixiZhang42** [firamath/firamath#39]
This is a very similar issue from https://github.com/alif-type/libertinus/issues/63

> The math operators are rather small compared to other math fonts. This might have been OK for the text font, but not so much for the math font.

IMHO Fira Math experiences the same flaws (in particular, the `+`, `-`, `=`, etc. signs are too small to be legible *in math*).

Below is the PDF file consisting of the changes made in https://github.com/alif-type/libertinus/pull/272

- https://github.com/libertinus-fonts/libertinus/files/3104834/operators_compare.pdf

The priority of Fira Math at this stage is to include more glyphs. So it will be better to start drawing new glyphs in a larger design space.

**Comment by stone-zeng** [comment]
I have already noticed this issue:

![image](https://user-images.githubusercontent.com/18233088/58650560-96586880-8341-11e9-9ba7-5fd5ee680d3e.png)

The original glyphs from FiraSans/FiraGO are small, and the new drawn ones are actually not consistent. I think the size of `\cap`, `\cup` etc is appropriate; `\in`, `\subset` are a little too bit large?

**Comment by Cheko-Canales** [comment]
I fondly agree. Math operators are small. I believe that bigger math operators (especially +, = and -) help to a comfortable and easy reading.

**Comment by stone-zeng** [comment]
I tried to modify some of the operators:

![image](https://user-images.githubusercontent.com/18233088/62384262-7da84100-b584-11e9-91c2-f37bbbeea89c.png)

Compared with the original one:

![image](https://user-images.githubusercontent.com/18233088/62384357-c2cc7300-b584-11e9-80f5-f3b82f2d3469.png)

Do you think they are OK or still need further modification? @RuixiZhang42 @Cheko-Canales

**Comment by RuixiZhang42** [comment]
@stone-zeng The `+` and `-` signs look good (not sure about why there are two `-`’s). However, I find the proportions of `\pm`, `\mp`, `\times` and `\div` a bit off. Of course, the following comments are subjectively based on my visual impression.

- Overall comment: Operators should *look* harmonious. The more complicated operators should be slightly smaller than the direct results of combining simpler ones, to create optical balance. (Under certain bounding box constraints in alignment, of course.)
- On `\pm` and `\mp`: More vertical space is needed between `+` and `-` signs. If moving `+` and `-` further apart results in a “too-high-and-too-ugly” glyph, then an alternative adjustment is to shorten the stem of `+` that is closest to `-`. (Remember the goal is to make the `+` in `\pm` and `\mp` *look* “squarish”.)
- On `\times`: It looks smaller compared with `+` and `\div`. A slight enlargement may be preferred.
- On `\div`: The two dots could be slightly further away from the bar, and/or the bar could be slightly shorter.

**Comment by Cheko-Canales** [comment]
![times](https://user-images.githubusercontent.com/51210432/62500974-4c12be00-b7ae-11e9-9910-3375c5a32ce3.png)
Hi!
In general:
To my taste I & criteria, the size is perfect.
The combined operators must remain in the same size in order to give a visual coherence among them.
In particular:
Only in the \times sing, I suggest a size that fits into a square that fits the \+ sing too.
I think that the vertical space between the \pm and \mp sings should be increased a little bit more.
The \div, \=, \+ and \-  sings must use the same horizontal line. 
 
Great work. I really appreciated your efforts and passion to every detail.
I will keep suggesting future upgrades and sharing my personal opinion.

**Comment by stone-zeng** [comment]
Thank you for the suggestions! I further modified them accordingly, and a comparison is as following:

![image](https://user-images.githubusercontent.com/18233088/62546326-da15a400-b895-11e9-9561-fe593cca5ee7.png)

- `\times`: enlarged a little, but still not exactly the same size as `+`
- `\div`: the distances between dots and bar are increased slightly (only 2 upm), although I don't think one may notice it...
- `\pm` & `\mp`: make `+` and `-` smaller and more separated

In some degree your opinions are contradicted so I am not able to fulfill all the suggestion. One thing need to mention is that, now these glyphs are still smaller compared with other math fonts, and I'm not sure whether it's ok:

![image](https://user-images.githubusercontent.com/18233088/62547731-45f90c00-b898-11e9-95a0-032756df2edd.png)

On the other hand, some more characters are redesigned:

![image](https://user-images.githubusercontent.com/18233088/62547349-a76cab00-b897-11e9-9f27-ae3e5b492177.png)

![image](https://user-images.githubusercontent.com/18233088/62548167-f2d38900-b898-11e9-9f5a-428c8987d8ab.png)

Hope you enjoy them and as before, further suggestions are welcome.

**Comment by YuanshengZhao** [comment]
This looks much better.

IMO,
Since =, < are modified, the curved version of them should also change, such as sim. Possibly, something like \cup, \in are also necessary. [ I know that it will be a huge project, though...]

In the same way as ± and +, symbols like ≤,≡ may be modified accordingly, I.e. the upper part of ≤ being contracted, and the spacing of bars in ≡ being smaller.

**Comment by Cheko-Canales** [comment]
They really look much better than the originals. **Great job**.
**Version 2 is the one I like.**
And I agree on the idea that the symbols in a math font should have a proper size, therefore a little increase in the size would be appropriated.
Furthermore, I believe **these symbols should be monospaced**.

**Comment by RuixiZhang42** [comment]
@Cheko-Canales 
> Furthermore, I believe **these symbols should be monospaced**.

I agree with this but only to a certain extent. The symbols should be monospaced *within groups*. It is not ideal to force `≪` (U+226A) to share the same width with `<` (U+003C). But the group containing `<` (U+003C), `≤` (U+2264), `≦` (U+2266), `≨` (U+2268), etc., along with the equal-related signs and greater-than-related signs should be monospaced. Another group is from `⊕` (U+2295) to `⊡` (U+22A1).

**Comment by stone-zeng** [comment]
> Furthermore, I believe **these symbols should be monospaced**.

> I agree with this but only to a certain extent. The symbols should be monospaced *within groups*...

This is exactly what I plan to do. I have moved it to #43, so if you have more comments in this topic please go there.
