### ISSUE TITLE
Roadmap for multiple-weight

### ISSUE THREAD

**Issue by stone-zeng** [firamath/firamath#4]
I think it's time to add more weights.

| Weight | Units | CSS | Bold weight | Units | CSS |
|:-:|:-:|:-:|:-:|:-:|:-:|
| Light | 58 | 300 | Regular | 92 | 400 |
| Regular | 92 | 400 | Bold | 158| 700 |
| Medium | 128| 500 | Heavy | 198 | 900 |
| Bold | 158| 700 | Ultra | 222 | 950 |

Something need to consider:

- Whether the bold weights are suitable (`mathbf`, e.g. for vectors and matrices)?
- Are these four weights enough?
- Should I add the condensed version (in FiraSans, but not in FiraGO)?

**Comment by thymaro** [comment]
How about joining the FiraGO team and merging the two projects into one? I mean no offense by this question, I just really don't have an understanding of how things (legal, technical, whatever) work around developing open type faces. Btw, I very much might use of Fira Math in my thesis. I think it's beautiful and Sans types have a crisp feeling of modernness about them.

**Comment by stone-zeng** [comment]
A simple test:

![image](https://user-images.githubusercontent.com/18233088/40574361-f3aa8548-6102-11e8-8670-75c2377b46c5.png)

**Comment by stone-zeng** [comment]
@thymaro I don't know how to join them, and whether it's necessary. At present, I just do the font for fun. Actually, I don't quitely understand the "things" you mentioned either.

**Comment by stone-zeng** [comment]
I plan to add thin weight as well:

| Weight | Units | CSS | Bold weight | Units | CSS |
|:-:|:-:|:-:|:-:|:-:|:-:|
| Thin | 22 | 100 | ExtraLight | 46 | 250 |

![image](https://user-images.githubusercontent.com/18233088/40820463-442bcb8c-6593-11e8-9a5e-85ac1464eb89.png)

**Comment by beojan** [comment]
Any idea when these might be ready (even if it's an automatic transformation)?

A light version would fit in better with the Metropolis default (Fira Sans Light).

**Comment by stone-zeng** [comment]
I have no plan to finish all the weights recently. All the weights should be generated via interpolation, but I am still considering how to implement it. Maybe in a long time (almost half a year), only regular is available.

**Comment by stone-zeng** [comment]
For alphabets and some of the symbols, I have copied from Fira Sans into Fira Math (see ac440e13348499c17cc4d2ceee34e0ca2f34522e). The `MATH` table, more symbols, as well as an overall check (e.g. metric, accent position, etc) are still on going.

Note that I have extended the family to 12 styles, which is consistent with the original Fira Sans (Hair, Eight, Four and Two are removes since they are too thin and not practically useful). ExtraBold, Heavy and Ultra do not have corresponding "bold" version (for mathematical use), so I just make these positions to be empty.

The weights are as following:

![image](https://user-images.githubusercontent.com/18233088/48068183-1c2d8e80-e20d-11e8-9994-d3f41d42b766.png)

| Weight     | Bold weight |
|:----------:|:-----------:|
| Thin       | ExtraLight  |
| UltraLight | Light       |
| ExtraLight | Book        |
| Light      | Regular     |
| Book       | Medium      |
| Regular    | Bold        |
| Medium     | ExtraBold   |
| SemiBold   | Heavy       |
| Bold       | Ultra       |
| ExtraBold  | *(empty)*   |
| Heavy      | *(empty)*   |
| Ultra      | *(empty)*   |

**Comment by beojan** [comment]
You could copy the missing glyphs from regular until the weights are finished. This prevents missing characters in text.

**Comment by stone-zeng** [comment]
Now the `weights` branch has been merged into `master`, since all the fonts are valid when loaded via `unicode-math`. If there are any problems, please commented in #27.
