### ISSUE TITLE
Remove U+FEFF ZERO WIDTH NO-BREAK SPACE

### ISSUE THREAD

**Issue by stone-zeng** [firamath/firamath#40]
At present U+FEFF ZERO WIDTH NO-BREAK SPACE is leave as an empty glyph (only in regular weight). Should I keep this, or simply remove it? Do I need to consider such special things when design a font?

**Comment by bwiernik** [comment]
It's a useful character to force equations to not break across lines.

**Comment by stone-zeng** [comment]
U+FEFF should be interpreted as the [Byte order mark](https://en.wikipedia.org/wiki/Byte_order_mark). The use of ZERO WIDTH NON-BREAKING SPACE (ZWNBSP) is deprecated and therefore "the use of U+2060 WORD JOINER is strongly preferred over ZWNBSP for expressing word joining semantics since it cannot be confused with a BOM".

See <http://www.unicode.org/faq/utf_bom.html#BOM>.

**Comment by stone-zeng** [comment]
Finally I decided to remove it.
