### ISSUE TITLE
Limit (\lim) operator

### ISSUE THREAD

**Issue by daturkel** [firamath/firamath#41]
There appears to be no symbol for the lim operator, which I would expect to render basically just as the non-italic letters `lim`. Is there an easy workaround for this?

**Comment by stone-zeng** [comment]
`\lim` is just the three letters `l`, `i` and `m`. So may use it with text font:

```latex
\documentclass{article}
\usepackage{amsmath,unicode-math}
\setmainfont{FiraSans-Regular.otf}
\setmathfont{FiraMath-Regular.otf}
\begin{document}
\[ \lim_{x\to\infty} \]
\end{document}
```

or by math font (the spacing may be not correct):

```latex
\documentclass{article}
\usepackage{amsmath,unicode-math}
\unimathsetup{mathrm=sym}
\setmathfont{FiraMath-Regular.otf}
\begin{document}
\[ \lim_{x\to\infty} \]
\end{document}
```

![image](https://user-images.githubusercontent.com/18233088/59192411-e7275700-8bb4-11e9-8974-3a68fe21f532.png)

PS: Mathematica font takes `lim` as a single character, which has the code point U+F438 (in Private Use Area).
