### ISSUE TITLE
Make some math operators monospaced

### ISSUE THREAD

**Issue by stone-zeng** [firamath/firamath#43]
Some math operators should be monospaced because of the requirement for alignment in formulae. Note that not all the binary/relation characters should be monospaced, e.g. `≪` need to be longer than `<` (at least in Fira Math).

See #39.

**Comment by RuixiZhang42** [comment]
Isn’t there already an issue? https://github.com/firamath/firamath/issues/19

**Comment by stone-zeng** [comment]
oops...
