### ISSUE TITLE
Position of sub-/superscript

### ISSUE THREAD

**Issue by stone-zeng** [firamath/firamath#45]
Consider `$x_i - x_i^*$`:

![image](https://user-images.githubusercontent.com/18233088/65381631-1f980e80-dd28-11e9-8f8d-19ef86ab4cea.png)

The `_i` in the first one is lower than the second one.

[From [Zhihu](https://www.zhihu.com/question/46196562)]

**Comment by YuanshengZhao** [comment]
This is not a bug but feature of math table, which is a compromise among all constants associated with sub/superscripts, especially subSuperscriptGapMin.

However, this behavior is not desired. Modification on these constants is needed.

**Comment by hvoss49** [comment]
in such a case use

`\[  x_i^{}  x_i^* \]`

[image: Bildschirmfoto vom 2019-09-22 08-17-51.png]

Am So., 22. Sept. 2019 um 06:55 Uhr schrieb Yuansheng Zhao <
notifications@github.com>:

**Comment by hvoss49** [comment]
in such a case use

`\[  x_i^{}  x_i^* \]`

![Bildschirmfoto vom 2019-09-22 08-17-51](https://user-images.githubusercontent.com/12891199/65383180-bad1b980-dd11-11e9-8141-dad8dd24b445.png)
