### ISSUE TITLE
Wrong positioning of \dot{\symbf{V}

### ISSUE THREAD

**Issue by kia999** [firamath/firamath#47]
Wrong positioning of \dot over \symbf{V} in lualatex.

**Comment by stone-zeng** [comment]
I can't see your problem:

```tex
\documentclass{article}
\usepackage{amsmath,unicode-math}
\setmathfont{FiraMath-Regular.otf}
\begin{document}
\csname c_sys_engine_str\endcsname\
Text $\dot{\symbf{V}} + \ddot{\symbf{V}} + \dddot{\symbf{V}}$
\[ \dot{\symbf{V}} + \ddot{\symbf{V}} + \dddot{\symbf{V}} \]
Text $\dot{\symbfit{V}} + \ddot{\symbfit{V}} + \dddot{\symbfit{V}}$
\[ \dot{\symbfit{V}} + \ddot{\symbfit{V}} + \dddot{\symbfit{V}} \]
Text $\dot{\symbf{v}} + \ddot{\symbf{v}} + \dddot{\symbf{v}}$
\[ \dot{\symbf{v}} + \ddot{\symbf{v}} + \dddot{\symbf{v}} \]
Text $\dot{\symbfit{v}} + \ddot{\symbfit{v}} + \dddot{\symbfit{v}}$
\[ \dot{\symbfit{v}} + \ddot{\symbfit{v}} + \dddot{\symbfit{v}} \]
\end{document}
```

![image](https://user-images.githubusercontent.com/18233088/70866102-53d64080-1fa0-11ea-9bdc-0aab41d7398d.png)

The font tested here is v0.3.2 from TeX Live.

**Comment by kia999** [comment]
Dear Xiangdong Zeng
I am sorry,

wrong positioning was observed for \dot{\mathbf{V}},  \dot{\symbf{V}}
yields correct output.

Igor A. Kotelnikov
igor.kotelnikov@gmail.com

Budker Institute of Nuclear Physics
Novosibirsk, 630090, Russia
tel: +7 383 3294268 (office)
mobile: +7 913 933 24 84
(also WhatsApp, WeChat)



пн, 16 дек. 2019 г. в 00:09, Xiangdong Zeng <notifications@github.com>:

**Comment by kia999** [comment]
Although for Stix Two I see correct positioning even in case of
\dot{\mathbf{V}}.

Igor A. Kotelnikov
igor.kotelnikov@gmail.com

Budker Institute of Nuclear Physics
Novosibirsk, 630090, Russia
tel: +7 383 3294268 (office)
mobile: +7 913 933 24 84
(also WhatsApp, WeChat)



пн, 16 дек. 2019 г. в 09:22, Igor A. Kotelnikov <igor.kotelnikov@gmail.com>:

**Comment by stone-zeng** [comment]
`\mathrm` by default will use the text fonts, which may not contain the enough metric information for correct position.

More details are described in the [documentation](http://mirrors.ctan.org/macros/latex/contrib/unicode-math/unicode-math.pdf) of `unicode-math` package (section 3.1).
