### ISSUE TITLE
Missed math symbols \bot and \perp

### ISSUE THREAD

**Issue by kia999** [firamath/firamath#48]
Math symbols \bot and \perp are printed as `?`.

**Comment by stone-zeng** [comment]
`\top` (&#x22a4;) and `\bot` (&#x22a5;) are not created, but `\perp` (&#x27c2;) has been added already. Could please provide more information, e.g. version of the font, and a piece of code that can reveal your problem?

**Comment by kia999** [comment]
I am using most recent version of MikTeX. Fira fonts came with MikTeX. Problem with \perp was resolved after removing the command  

%\def\perp{\mathrel\bot}

which I added long ago since \pert symbol was missed in Cambria Math. Other lines of my code follow:

    \usepackage{fontspec}
    \defaultfontfeatures{Ligatures={TeX},Renderer=Basic}
    \setmainfont{Fira Sans}

    \usepackage[math-style=ISO,bold-style=ISO]{unicode-math}
    \setmathfont[Color=000066,Scale=MatchLowercase]{Fira Math Regular}
    \setmathfont[range=\int,StylisticSet=1]{Fira Math Regular}

    \begin{equation}
    \label{1:01}
    \tau_{n} \approx \sqrt{2\tau_{\|}\tau_{\bot}}
    \perp\bot
    .
    \end{equation}

**Comment by stone-zeng** [comment]
I will add them later.

**Comment by hvoss49** [comment]
Instaead of
   `%\def\perp{\mathrel\bot}`

you should have used

`\providecommand\perp{\mathrel\bot}`

then you get no error if `\perp` was already defined.
