### ISSUE TITLE
Possibly wrong mapping of characters in OpenType output

### ISSUE THREAD

**Issue by sunnyssk** [firamath/firamath#5]
I haven't looked into any source file yet, just had a test in MS Word. It seems that for italic characters the following three glyphs are mapped to wrong places:

"\varepsilon" 1D716
"\phi" 1D719
"\varrho" 1D71A

Hope they could be corrected.

**Comment by stone-zeng** [comment]
This image is from Unicode 11 code chart:

![image](https://user-images.githubusercontent.com/18233088/41755880-106985c6-760c-11e8-934a-1d3ed829d56e.png)

And this is from FiraMath Regular:

![image](https://user-images.githubusercontent.com/18233088/41755942-51044242-760c-11e8-8279-adf8e268d3ad.png)

Compare with other math fonts (Latin Modern Math, XITS Math and TeX Gyre Pagella Math), they are also consistent:

![image](https://user-images.githubusercontent.com/18233088/41755996-97b21836-760c-11e8-8a72-06a6dda47f32.png)

So I don't think there are problems for these glyphs. Could please try other fonts (like Cambria Math) in Word, and see whether they have the same result?

**Comment by sunnyssk** [comment]
Below is what I have found in charmap of the Opentype release in MS Word:
![wrong-mapping](https://user-images.githubusercontent.com/19568216/41783285-81e72bb0-760a-11e8-8009-aa828e5cb4c7.png)
which is noticeably different from that of Cambria math:
![correct-mapping](https://user-images.githubusercontent.com/19568216/41783351-ac006e34-760a-11e8-9671-e8c9a215b0da.png)
They also behave as indicated by this map (i.e., wrong characters are displayed on screen for italic font).
Would it be an issue related only with the released .otf file?

**Comment by stone-zeng** [comment]
This is a bug in this release. I will update a release then.

**Comment by stone-zeng** [comment]
Please try the new release version. This problem should be fixed.

**Comment by sunnyssk** [comment]
Nicely fixed.
