### ISSUE TITLE
Problem with Acrobat reader

### ISSUE THREAD

**Issue by svenkat93** [firamath/firamath#53]
I am using lualatex.  When I try to view the file in Adobe Acrobat Reader(2020.012.20048), I get the error message *Cannot extract the embedded font `IKNDRR+FiraMath-Regular'. Some characters may not display or print correctly.*

**Comment by okumuralab** [comment]
MWE:

```
%#!lualatex
\documentclass{article}
\usepackage{unicode-math}
\setmathfont{Fira Math}
\begin{document}
$\{a\}$
\end{document}
```

**Comment by clerkma** [comment]
With a peek of the CFF table in FiraMath-Regular.otf (md5=`37dbbbe38d8141ddfe8cf54736e8b5a1`), I found that there are 70 empty `cntrmask` operators in bytecode. Any glyph which contains empty `cntrmask` operator can make the same error.

Related characters:
```
uni007D, uni00F7, uni20DB, uni20E8, uni2208, uni2209, uni220A, uni220B, uni220C, uni220D, uni2234 ...
```

A simple quick fix (using [fonttools](https://github.com/fonttools/fonttools)):
```
ttx -o FiraMath-Regular-New.xml FiraMath-Regular.otf
sed -i s/cntrmask//g FiraMath-Regular-New.xml
ttx FiraMath-Regular-New.xml
```

**Comment by stone-zeng** [comment]
It is from the `CounterMasks` data in the sfd files and I will remove them. This empty `cntrmask` will result in some other issues, for example the font may not display corretly in Glyphs or system preview.
