### ISSUE TITLE
List of supported glyphs?

### ISSUE THREAD

**Issue by cpitclaudel** [firamath/firamath#57]
Thanks for your work on this font!

Is there a list somewhere of all supported glyphs?  I'd like to use this font in a Beamer presentation, but since it's missing some symbols I need a fallback; it would be convenient to define the fallback font as the default and then use `\setmathfont{Fira Math}[range=…]`.

(Two of the glyphs I'm missing are ∃ and ∀)

**Comment by stone-zeng** [comment]
It can be found in firamath-specimen.pdf, see [releases](https://github.com/firamath/firamath/releases).
