### ISSUE TITLE
OTF-v0.2: wrong intersection behavior in \oint, \oiint and \oiiint

### ISSUE THREAD

**Issue by sunnyssk** [firamath/firamath#6]
Nice to see these new characters implemented, however there are problems related with them.

Please see the screenshot below for details. The problem is found in the v0.2 OTF release.
![intersect](https://user-images.githubusercontent.com/19568216/41814989-b6d4e566-772b-11e8-84f0-1f7344fbd816.png)

This problem also seem to exist in the arrows with a slash (U+219A, U+219B, U+21AE).

**Comment by stone-zeng** [comment]
This problem doesn't occur when using TeX, but can be found in MS Word. I will try to find the reason.

**Comment by be5invis** [comment]
Only TTF and CFF2 supports non-zero filling, which allows overlapping contours.
So merge the contours, remove the overlap.

**Comment by stone-zeng** [comment]
Detail can be found in:

- <https://docs.microsoft.com/en-us/typography/opentype/spec/ttch01#the-scan-converter>
- <https://fontforge.org/docs/tutorial/editexample2.html>
- <https://www.zhihu.com/question/22958337/answer/34414662> (in Chinese)
