### ISSUE TITLE
Other weights of Fira Math(like Light or Bold) are lack of some characters

### ISSUE THREAD

**Issue by Firestar-Reimu** [firamath/firamath#60]
Other weights of Fira Math(like Light or Bold) are lack of some characters, like:
![图片](https://user-images.githubusercontent.com/65082432/112282476-1e9bc080-8cc2-11eb-97ab-66957a777278.png)

**Comment by stone-zeng** [comment]
I'm now working on the new multiple weights version, see #56. If you want try them now, please download the latest dev version from [Actions](https://github.com/firamath/firamath/actions). Currently there are still many things to do, especially the spacing and kerning.
