### ISSUE TITLE
The thin/regular/medium/bold/extrabold etc. are marked as thin 

### ISSUE THREAD

**Issue by Firestar-Reimu** [firamath/firamath#66]
![Screenshot_20210726_155154](https://user-images.githubusercontent.com/65082432/126952984-af581c2b-3df4-4df3-9fc0-c8dd6889f5e8.png)

OS: Manjaro KDE, Installed: all the FiraMath 0.4 OTF fonts from two four six eight to extrabold

**Comment by stone-zeng** [comment]
Could you please tell me where did you download these fonts (e.g. which builds in GitHub Actions)?

**Comment by Firestar-Reimu** [comment]
It is installed than June 29. I install it via Github Actions.

Then it is Github Actions #82.

**Comment by Firestar-Reimu** [comment]
Thanks! I saw the v1.0 milestone, will 0.3.x and 0.4.x be merged all into v1.0?

**Comment by stone-zeng** [comment]
> Thanks! I saw the v1.0 milestone, will 0.3.x and 0.4.x be merged all into v1.0?

They have already been merged. But since I switched to glyphs and almost re-drawn all the things, there can be a lot of changes from them.

**Comment by Firestar-Reimu** [comment]
Maybe you can make a github action/alpha release for us to download it easier, the old 0.4.x release is too old.

**Comment by stone-zeng** [comment]
You can download from actions now, but the release still need some work to do.
