### ISSUE TITLE
Bold version

### ISSUE THREAD

**Issue by hvoss49** [firamath/firamath#9]
Using the `FiraMath-Bold` I'll get with

```
\documentclass[border=5mm,preview,varwidth]{standalone}
\usepackage{amsmath}
\usepackage[no-math]{fontspec}
\usepackage[math-style=ISO,bold-style=ISO,mathrm=sym]{unicode-math}
\setsansfont{Fira Sans}
\setmathfont{FiraMath-Regular.otf}%
\setmathfont[version=bold]{FiraMath-Bold.otf}%
%\setmathfont[version=bold]{FiraMath-Bold2.otf}
\begin{document}
\[ \hat{f}(\omega) = \frac1{\sqrt{2\symup{\pi}}} \int\limits_{-\infty}^{+\infty} f(x) 
\symup{e}^{-\symup{i}\omega x} \sin(x)\, \symup dx \]

\boldmath
\[ \hat{f}(\omega) = \frac1{\sqrt{2\symup{\pi}}} \int\limits_{-\infty}^{+\infty} f(x) 
\symup{e}^{-\symup{i}\omega x} \sin(x) \,\symup dx \]
\end{document}
```

![bildschirmfoto vom 2018-06-30 10-57-04](https://user-images.githubusercontent.com/12891199/42123573-87ff0612-7c54-11e8-80e2-0b33287e0b7f.png)

Creating a bold version from the `FiraMath-Regular`  by changing the weight and saving it as `[FiraMath-Bold2.otf`](http://archiv.dante.de/~herbert/FiraMath-Bold2.otf) I'll get 

![bildschirmfoto vom 2018-06-30 10-57-35](https://user-images.githubusercontent.com/12891199/42123587-c2e429f6-7c54-11e8-88a6-79abca39be34.png)

IS this the intended behaviour of your bold version?

**Comment by stone-zeng** [comment]
Bold weight (as well as Heavy, Light and Thin) hasn't been finished and should not be used at present. I will try to update them in the future.

**Comment by hvoss49** [comment]
Couldn't it be an option to create the different weights with fontforge from Regular as base and call it a prerelease?

**Comment by stone-zeng** [comment]
The faked bold version is far from elegant and beautiful, so I don't want to use them.

I will close this issues, but more ideas and suggestions are welcome and can be added in #4.
